import type { User, Post, Comment, Report, AdminAction, ModerationPolicy, DashboardStats } from "./types"

// Mock Users
export const mockUsers: User[] = [
  {
    _id: "u1",
    username: "john_doe",
    email: "john@example.com",
    avatar: "/male-avatar.png",
    role: "user",
    status: "active",
    canComment: true,
    warningCount: 0,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    _id: "u2",
    username: "jane_smith",
    email: "jane@example.com",
    avatar: "/diverse-female-avatar.png",
    role: "user",
    status: "locked",
    canComment: false,
    warningCount: 3,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-12-10"),
  },
  {
    _id: "u3",
    username: "bob_wilson",
    email: "bob@example.com",
    avatar: "/man-avatar.png",
    role: "user",
    status: "suspended",
    banUntil: new Date("2024-12-25"),
    canComment: false,
    warningCount: 5,
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-12-14"),
  },
  {
    _id: "u4",
    username: "alice_johnson",
    email: "alice@example.com",
    avatar: "/diverse-woman-avatar.png",
    role: "moderator",
    status: "active",
    canComment: true,
    warningCount: 0,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    _id: "u5",
    username: "admin_user",
    email: "admin@example.com",
    avatar: "/admin-avatar.png",
    role: "admin",
    status: "active",
    canComment: true,
    warningCount: 0,
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    _id: "u6",
    username: "super_Dat",
    email: "superadmin@example.com",
    avatar: "/superadmin-avatar.jpg",
    role: "superadmin",
    status: "active",
    canComment: true,
    warningCount: 0,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
]

// Mock Posts
export const mockPosts: Post[] = [
  {
    _id: "p1",
    authorId: "u1",
    author: mockUsers[0],
    content: "This is a normal post about technology trends in 2024.",
    status: "published",
    reportCount: 0,
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-10"),
  },
  {
    _id: "p2",
    authorId: "u2",
    author: mockUsers[1],
    content: "Inappropriate content that has been reported multiple times.",
    status: "under_review",
    reportCount: 5,
    createdAt: new Date("2024-12-12"),
    updatedAt: new Date("2024-12-14"),
  },
  {
    _id: "p3",
    authorId: "u3",
    author: mockUsers[2],
    content: "This post has been removed due to policy violations.",
    status: "removed",
    reportCount: 10,
    createdAt: new Date("2024-12-08"),
    updatedAt: new Date("2024-12-13"),
  },
  {
    _id: "p4",
    authorId: "u1",
    author: mockUsers[0],
    content: "Another great post about web development best practices.",
    status: "published",
    reportCount: 1,
    createdAt: new Date("2024-12-14"),
    updatedAt: new Date("2024-12-14"),
  },
]

// Mock Comments
export const mockComments: Comment[] = [
  {
    _id: "c1",
    postId: "p1",
    authorId: "u2",
    author: mockUsers[1],
    content: "Great post! I totally agree with your points.",
    visible: true,
    reportCount: 0,
    createdAt: new Date("2024-12-11"),
  },
  {
    _id: "c2",
    postId: "p1",
    authorId: "u3",
    author: mockUsers[2],
    content: "This comment contains spam links and has been hidden.",
    visible: false,
    reportCount: 3,
    createdAt: new Date("2024-12-11"),
  },
  {
    _id: "c3",
    postId: "p2",
    authorId: "u1",
    author: mockUsers[0],
    content: "I reported this post for inappropriate content.",
    visible: true,
    reportCount: 0,
    createdAt: new Date("2024-12-13"),
  },
]

// Mock Reports
export const mockReports: Report[] = [
  {
    _id: "r1",
    reporterId: "u1",
    reporter: mockUsers[0],
    targetType: "post",
    targetId: "68e7f3ebdfb62f57b778412d",
    targetName: "Tên Số 1",
    target: mockPosts[1],
    reason: "Inappropriate content - contains offensive language",
    status: "pending",
    createdAt: new Date("2024-12-14"),
  },
  {
    _id: "r2",
    reporterId: "u4",
    reporter: mockUsers[3],
    targetType: "comment",
    targetId: "68e7f3ebdfb62f57b778412d",
     targetName: "Tên Số 1",
    target: mockComments[1],
    reason: "Spam - contains promotional links",
    status: "reviewed",
    createdAt: new Date("2024-12-13"),
  },
  {
    _id: "r3",
    reporterId: "u1",
    reporter: mockUsers[0],
    targetType: "user",
    targetId: "u3",
     targetName: "Tên Số 1",
    target: mockUsers[2],
    reason: "Harassment - multiple threatening messages",
    status: "pending",
    createdAt: new Date("2024-12-15"),
  },
  {
    _id: "r4",
    reporterId: "u2",
    reporter: mockUsers[1],
    targetType: "post", targetName: "Tên Số 1",
    targetId: "p3",
    target: mockPosts[2],
    reason: "Misinformation - spreads false information",
    status: "reviewed",
    createdAt: new Date("2024-12-12"),
  },
  {
    _id: "r5",
    reporterId: "u3",
    reporter: mockUsers[2],
    targetType: "post",
    targetId: "p2", targetName: "Tên Số 1",
    reason: "Hate speech",
    status: "pending",
    createdAt: new Date("2024-12-14"),
  },
]

// Mock Admin Actions
export const mockAdminActions: AdminAction[] = [
  {
    _id: "a1",
    adminId: "u5",
    admin: mockUsers[4],
    actionType: "lock_user",
    targetType: "user",
    targetId: "u2",
    reason: "Multiple policy violations",
    createdAt: new Date("2024-12-14T10:30:00"),
  },
  {
    _id: "a2",
    adminId: "u4",
    admin: mockUsers[3],
    actionType: "hide_comment",
    targetType: "comment",
    targetId: "c2",
    reason: "Spam content",
    createdAt: new Date("2024-12-13T15:45:00"),
  },
  {
    _id: "a3",
    adminId: "u5",
    admin: mockUsers[4],
    actionType: "remove_post",
    targetType: "post",
    targetId: "p3",
    reason: "Severe policy violation",
    createdAt: new Date("2024-12-13T09:20:00"),
  },
  {
    _id: "a4",
    adminId: "u6",
    admin: mockUsers[5],
    actionType: "suspend_user",
    targetType: "user",
    targetId: "u3",
    reason: "Repeated harassment",
    createdAt: new Date("2024-12-14T14:00:00"),
  },
  {
    _id: "a5",
    adminId: "u4",
    admin: mockUsers[3],
    actionType: "warning",
    targetType: "user",
    targetId: "u2",
    reason: "First warning for inappropriate behavior",
    createdAt: new Date("2024-12-10T11:30:00"),
  },
]

// Mock Moderation Policy
export const mockModerationPolicy: ModerationPolicy = {
  autoHideThreshold: 5,
  autoSuspendDays: 7,
  maxWarnings: 3,
  createdAt: new Date("2024-12-01"),
}

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  reportsToday: 12,
  reportsThisWeek: 47,
  contentUnderReview: 8,
  lockedUsers: 15,
  suspendedUsers: 5,
  topReportedUsers: [
    { user: mockUsers[2], count: 12 },
    { user: mockUsers[1], count: 8 },
    { user: mockUsers[0], count: 3 },
  ],
  topReportedPosts: [
    { post: mockPosts[2], count: 10 },
    { post: mockPosts[1], count: 5 },
    { post: mockPosts[3], count: 1 },
  ],
  reportsByDay: [
    { date: "2024-12-09", count: 5 },
    { date: "2024-12-10", count: 8 },
    { date: "2024-12-11", count: 12 },
    { date: "2024-12-12", count: 7 },
    { date: "2024-12-13", count: 15 },
    { date: "2024-12-14", count: 10 },
    { date: "2024-12-15", count: 12 },
  ],
  reportsByType: [
    { type: "Inappropriate Content", count: 25 },
    { type: "Spam", count: 18 },
    { type: "Harassment", count: 12 },
    { type: "Misinformation", count: 8 },
    { type: "Other", count: 5 },
  ],
}
